const COMPANIES = {
  DP3: 'DP3',
  CLH: 'CLH',
  CHS: 'CHS',
  STC: 'STC',
  SKV: 'SKV',
  SED: 'SED',
  RAL: 'RAL',
  PNJ: 'PNJ',
  IDV: 'IDV',
  DSN: 'DSN',
  DPG: 'DPG',
  VPS: 'VPS',
  TV1: 'TV1',
  TRA: 'TRA',
  TCM: 'TCM',
  PGS: 'PGS',
  OPC: 'OPC',
  HUG: 'HUG',
  CKD: 'CKD',
  X20: 'X20',
  VPD: 'VPD',
  VIF: 'VIF',
  SNZ: 'SNZ',
  SFI: 'SFI',
  REE: 'REE',
  PVT: 'PVT',
  INN: 'INN',
  IDP: 'IDP',
  HTC: 'HTC',
  GDA: 'GDA',
  EMS: 'EMS',
  EID: 'EID',
  DVN: 'DVN',
  ACV: 'ACV',
  VIN: 'VIN',
  VGG: 'VGG',
  SAB: 'SAB',
  PTI: 'PTI',
  PPS: 'PPS',
  LBM: 'LBM',
  IDC: 'IDC',
  HDB: 'HDB',
  BID: 'BID',
  ACG: 'ACG',
  PSD: 'PSD',
  M10: 'M10',
  DPM: 'DPM',
  DBD: 'DBD',
  BWE: 'BWE',
  BTT: 'BTT',
  RENTAL_REPORT: 'RENTAL_REPORT',
};

const CAFEF_API = `https://cafef.vn/du-lieu/Ajax/CongTy/BaoCaoTaiChinh.aspx?sym=`;

export { COMPANIES, CAFEF_API };